"""
Analysis report generator for ChemSpectra Agent.
Produces structured JSON and Markdown reports with DOI-cited evidence.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone


def generate_report(
    sample_context: str,
    matches: list[dict],
    chemical_reasoning: str,
    verification: dict,
) -> str:
    """Generate a Markdown-formatted FTIR analysis report."""

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    top = matches[0] if matches else {}

    report = f"""# FTIR Spectral Analysis Report

**Report ID:** FTIR-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}
**Generated:** {now}
**Analyst:** ChemSpectra AI Agent (human-confirmed)

---

## 1. Sample Information

{_section_sample(sample_context)}

---

## 2. Analysis Method

- **Technique:** Fourier Transform Infrared Spectroscopy (FTIR)
- **Search Database:** FTIR.fun reference library (130,000+ spectra)
- **Matching Algorithm:** Full-spectrum correlation + peak-based verification
- **AI Review:** Qwen-Max chemical reasoning engine
- **Quality Control:** PCA-weighted peak verification

---

## 3. Results Summary

| Rank | Material | CAS | Score | Confidence |
|------|----------|-----|-------|------------|
{_table_matches(matches)}

**Best Match:** {top.get('name', 'Unknown')}
**CAS Number:** {top.get('cas', 'N/A')}
**Similarity Score:** {top.get('score', 0):.3f}

---

## 4. Chemical Reasoning

{chemical_reasoning or 'No chemical reasoning provided.'}

**AI Verdict:** {verification.get('verdict', 'needs_review')}

---

## 5. Evidence & References

{_section_evidence(top)}

---

## 6. Quality Control Notes

- PCA principal component analysis applied for peak weighting
- Functional group assignments verified against IR correlation tables
- Mixture detection: {'Potential mixture detected' if _is_mixture(matches) else 'Single component indicated'}
- AI confidence adjustment applied

---

## 7. Human-in-the-Loop Confirmation

✅ **Confirmed by human analyst**
This report was reviewed and accepted by a qualified analyst before finalization.

---

*Report generated by ChemSpectra Agent (Qwen Cloud Hackathon — Track 4: Autopilot Agent)*
*Powered by FTIR.fun spectral library & Alibaba Cloud Qwen API*
"""
    return report


def _section_sample(context: str) -> str:
    if not context:
        return "Sample context not provided."
    return f"- **Description:** {context}"


def _table_matches(matches: list[dict]) -> str:
    if not matches:
        return "| — | No matches found | — | — | — |"
    rows = []
    for m in matches[:5]:
        name = m.get("name", "?")
        cas = m.get("cas", "N/A")
        score = m.get("score", 0)
        conf = m.get("confidence", score)
        rows.append(f"| {name} | {cas} | {score:.3f} | {conf:.1%} |")
    return "\n".join(rows)


def _section_evidence(top: dict) -> str:
    evidence = top.get("evidence", [])
    explanations = top.get("peak_explanations", [])
    if not evidence and not explanations:
        return "No explicit evidence entries available for this match."

    lines = []
    for exp in explanations[:5]:
        if isinstance(exp, dict):
            peak = exp.get("peak", "?")
            group = exp.get("functional_group", "?")
            doi = exp.get("doi", "")
            lines.append(
                f"- Peak {peak} cm⁻¹ → {group}"
                + (f" [DOI: {doi}](https://doi.org/{doi})" if doi else "")
            )
    return "\n".join(lines) if lines else "No peak explanations available."


def _is_mixture(matches: list[dict], threshold: float = 0.05) -> bool:
    """Detect if results suggest a mixture (scores are very close)."""
    if len(matches) < 2:
        return False
    return abs(matches[0].get("score", 0) - matches[1].get("score", 0)) < threshold


def export_json(
    sample_context: str,
    matches: list[dict],
    chemical_reasoning: str,
    verification: dict,
    filepath: str = "report.json",
) -> str:
    """Export analysis results as structured JSON."""
    data = {
        "report_id": f"FTIR-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "sample_context": sample_context,
        "matches": matches,
        "chemical_reasoning": chemical_reasoning,
        "verification": verification,
        "human_confirmed": True,
    }
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return filepath
